services:
  - docker

language: generic

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -o config https://$GITHUB_ACCESS_TOKEN@raw.githubusercontent.com/iosdal/privaterepo/master/.kube/config
  - mkdir ${HOME}/.kube
  - cp config ${HOME}/.kube/config
  - docker build -t ivandal77/demo .

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push ivandal77/demo
  - kubectl version


  #- docker run iosdal/phoenix-kata